import "./globals.css";
import type { Metadata } from "next";

import TopNavigation from "@/components/TopNavigation";

export const metadata: Metadata = {
  title: "@Dynamic Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopNavigation />
        {children}
      </body>
    </html>
  );
}