"use client";
import "./globals.css";
// import type { Metadata } from "next";

import TopNavigation from "@/components/TopNavigation";
import Footer from "@/components/Footer";

import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";

// export const metadata: Metadata = { // client components can not have metadata
//   title: "@Dynamic Blog",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Toaster />
          <TopNavigation />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
